// opcode → scratchblocks 表示テキストのマッピング
// scratchblocks の構文: https://scratchblocks.github.io/
// 引数は [] で省略表現。実際の値は不要（ブロックの形が伝わればよい）

export const BLOCK_LABELS = {
    // ---- イベント ----
    event_whenflagclicked: 'when flag clicked',
    event_whenkeypressed: 'when [space v] key pressed',
    event_whenthisspriteclicked: 'when this sprite clicked',
    event_whenstageclicked: 'when stage clicked',
    event_whenbackdropswitchesto: 'when backdrop switches to [backdrop1 v]',
    event_whengreaterthan: 'when [loudness v] > (10)',
    event_whenbroadcastreceived: 'when I receive [message1 v]',
    event_broadcast: 'broadcast [message1 v]',
    event_broadcastandwait: 'broadcast [message1 v] and wait',

    // ---- 動き ----
    motion_movesteps: 'move (10) steps',
    motion_turnright: 'turn cw (15) degrees',
    motion_turnleft: 'turn ccw (15) degrees',
    motion_goto: 'go to [random position v]',
    motion_gotoxy: 'go to x: (0) y: (0)',
    motion_glideto: 'glide (1) secs to [random position v]',
    motion_glidesecstoxy: 'glide (1) secs to x: (0) y: (0)',
    motion_pointindirection: 'point in direction (90)',
    motion_pointtowards: 'point towards [mouse-pointer v]',
    motion_changexby: 'change x by (10)',
    motion_setx: 'set x to (0)',
    motion_changeyby: 'change y by (10)',
    motion_sety: 'set y to (0)',
    motion_ifonedgebounce: 'if on edge, bounce',
    motion_setrotationstyle: 'set rotation style [left-right v]',
    motion_xposition: '(x position)',
    motion_yposition: '(y position)',
    motion_direction: '(direction)',

    // ---- 見た目 ----
    looks_sayforsecs: 'say [Hello!] for (2) seconds',
    looks_say: 'say [Hello!]',
    looks_thinkforsecs: 'think [Hmm...] for (2) seconds',
    looks_think: 'think [Hmm...]',
    looks_switchcostumeto: 'switch costume to [costume1 v]',
    looks_nextcostume: 'next costume',
    looks_switchbackdropto: 'switch backdrop to [backdrop1 v]',
    looks_nextbackdrop: 'next backdrop',
    looks_changesizeby: 'change size by (10)',
    looks_setsizeto: 'set size to (100) %',
    looks_changeeffectby: 'change [color v] effect by (25)',
    looks_seteffectto: 'set [color v] effect to (0)',
    looks_cleargraphiceffects: 'clear graphic effects',
    looks_show: 'show',
    looks_hide: 'hide',
    looks_gotofrontback: 'go to [front v] layer',
    looks_goforwardbackwardlayers: 'go [forward v] (1) layers',
    looks_costumenumbername: '(costume [number v])',
    looks_backdropnumbername: '(backdrop [number v])',
    looks_size: '(size)',

    // ---- 音 ----
    sound_playuntildone: 'play sound [Meow v] until done',
    sound_play: 'start sound [Meow v]',
    sound_stopallsounds: 'stop all sounds',
    sound_changeeffectby: 'change [pitch v] effect by (10)',
    sound_seteffectto: 'set [pitch v] effect to (100)',
    sound_cleareffects: 'clear sound effects',
    sound_changevolumeby: 'change volume by (-10)',
    sound_setvolumeto: 'set volume to (100) %',
    sound_volume: '(volume)',

    // ---- 制御 ----
    control_wait: 'wait (1) seconds',
    control_repeat: 'repeat (10) {}',
    control_forever: 'forever {}',
    control_if: 'if <> then {}',
    control_if_else: 'if <> then {} else {}',
    control_wait_until: 'wait until <>',
    control_repeat_until: 'repeat until <> {}',
    control_stop: 'stop [all v]',
    control_start_as_clone: 'when I start as a clone',
    control_create_clone_of: 'create clone of [myself v]',
    control_delete_this_clone: 'delete this clone',

    // ---- 調べる ----
    sensing_touchingobject: '<touching [mouse-pointer v] ?>',
    sensing_touchingcolor: '<touching color [#ff0000] ?>',
    sensing_coloristouchingcolor: '<color [#ff0000] is touching [#0000ff] ?>',
    sensing_distanceto: '(distance to [mouse-pointer v])',
    sensing_askandwait: 'ask [What\'s your name?] and wait',
    sensing_answer: '(answer)',
    sensing_keypressed: '<key [space v] pressed?>',
    sensing_mousedown: '<mouse down?>',
    sensing_mousex: '(mouse x)',
    sensing_mousey: '(mouse y)',
    sensing_setdragmode: 'set drag mode [draggable v]',
    sensing_loudness: '(loudness)',
    sensing_timer: '(timer)',
    sensing_resettimer: 'reset timer',
    sensing_dayssince2000: '(days since 2000)',
    sensing_username: '(username)',

    // ---- 演算 ----
    operator_add: '((1) + (2))',
    operator_subtract: '((1) - (2))',
    operator_multiply: '((1) * (2))',
    operator_divide: '((1) / (2))',
    operator_random: '(pick random (1) to (10))',
    operator_gt: '<(1) > (2)>',
    operator_lt: '<(1) < (2)>',
    operator_equals: '<(1) = (2)>',
    operator_and: '<<> and <>>',
    operator_or: '<<> or <>>',
    operator_not: '<not <>>',
    operator_join: '(join [hello ] [world])',
    operator_letter_of: '(letter (1) of [apple])',
    operator_length: '(length of [apple])',
    operator_contains: '<[apple] contains [a]?>',
    operator_mod: '((10) mod (3))',
    operator_round: '(round (3.4))',
    operator_mathop: '([sqrt v] of (9))',

    // ---- 変数 ----
    data_variable: '(my variable)',
    data_setvariableto: 'set [my variable v] to (0)',
    data_changevariableby: 'change [my variable v] by (1)',
    data_showvariable: 'show variable [my variable v]',
    data_hidevariable: 'hide variable [my variable v]',

    // ---- リスト ----
    data_listcontents: '(my list)',
    data_addtolist: 'add [thing] to [my list v]',
    data_deleteoflist: 'delete (1) of [my list v]',
    data_deletealloflist: 'delete all of [my list v]',
    data_insertatlist: 'insert [thing] at (1) of [my list v]',
    data_replaceitemoflist: 'replace item (1) of [my list v] with [thing]',
    data_itemoflist: '(item (1) of [my list v])',
    data_itemnumoflist: '(item # of [thing] in [my list v])',
    data_lengthoflist: '(length of [my list v])',
    data_listcontainsitem: '<[my list v] contains [thing]?>',
    data_showlist: 'show list [my list v]',
    data_hidelist: 'hide list [my list v]',

    // ---- ペン拡張 ----
    pen_clear: 'erase all',
    pen_stamp: 'stamp',
    pen_penDown: 'pen down',
    pen_penUp: 'pen up',
    pen_setPenColorToColor: 'set pen color to [#ff0000]',
    pen_changePenColorParamBy: 'change pen [color v] by (10)',
    pen_setPenColorParamTo: 'set pen [color v] to (50)',
    pen_changePenSizeBy: 'change pen size by (1)',
    pen_setPenSizeTo: 'set pen size to (1)'
};
